### ISSUE TITLE
Integrate migration assistant with create-angular-template utility

### ISSUE THREAD

**Issue by psmyrdek** [ellamaolson/ngMigration-Assistant#18]
Hi all!

I really enjoy to see more projects related to the topic of AngularJS -> Angular migration. We all want to make jumping to the newer ship easier and faster. Since this project has much bigger chance to get more traction, I was wondering if it would be possible to integrate my toolkit with your solution.

As I see now, ngMigration-Assistant runs static analysis on top of given project to let you know which parts of it should be updated in order to work smoothly with newer Angular. While this knowledge is valuable, I think that we could automate whole process even more.

Few months ago I create two tools, which - I believe - could really enhance the current workflow of ngMigration-Assistant.
1. https://github.com/psmyrdek/create-angular-template
2. https://github.com/psmyrdek/ng-up

`create-angular-template` is a library which runs a set of transformations on your AngularJS templates preparing them for the new syntax.  `ng-if` gets transformed into `*ngIf`, `ng-repeat` into `*ngFor`, etc. All of this makes the process of manual updates much easier.

To make it even easier to use, I also created `ng-up`, which is a CLI utility combined from `create-angular-template` and yet another module responsible for preparing Anuglar providers for AngularJS services.

I believe it would be possible to somehow integrate both tools (at least `create-angular-template`) to automate the migration process and reduce the amount of time you need to spend on it. 

What do you think? I'm open for all kinds of suggestions.

**Comment by kfeinUI** [comment]
Neat. I also stumbled across this one last night, which looks to be a bit more robust in terms of the transformations:

https://github.com/erictsai6/angularjs-to-angular/

It's baffling that we never got anything official from Angular. I recall mention during ngConf that Google built tools (presumably look these) to help migrate their hundreds of apps, but for some reason never shared them. Wouldn't have to be some perfect solution that works right away for everyone. Just something like the above that is a reasonable foundation to expand upon to get it working for your codebase. 

Based on what it conveys today, I'm not sure how such tools would be tied in. It's a static report. Maybe if the intention is to grow it into a more robust and interactive toolbox, then it could work.

**Comment by ellamaolson** [comment]
Great idea, let's look into it further and see what we can do to incorporate the automation tools.
