### ISSUE TITLE
ngma not found

### ISSUE THREAD

**Issue by mermonkey** [ellamaolson/ngMigration-Assistant#4]
I'm probably missing something simple, but i get this on windows after doing the yarn add and trying to run ngma:
    'ngma' is not recognized as an internal or external command,

**Comment by ellamaolson** [comment]
Hmm... did you globally add ngma?

**Comment by kleinux** [comment]
I get this using npm too, but a workaround is running "npm run ngma" Angular cli has the same problem so I think it is something with my machine.

**Comment by ellamaolson** [comment]
I'm going to close this as @kleinux has answered it with:
**npm run ngma**
